name: glider
description: An opinionated Hacker News client.
version: 2.8.0+49
publish_to: none

environment:
  sdk: ">=3.13.0 <4.0.0"

dependencies:
  bloc: ^9.2.1
  bloc_presentation: ^1.1.2
  clock: ^1.1.2
  collection: any
  device_info_plus: ^13.2.0
  dynamic_color: ^1.9.0
  equatable: ^2.1.0
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.3.3
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_markdown_plus: ^1.0.12
  flutter_secure_storage: ^11.0.0
  formz: ^0.8.1
  glider_data:
    path: packages/glider_data
  glider_domain:
    path: packages/glider_domain
  go_router: ^17.5.0
  google_fonts: ^8.2.1
  http: ^1.6.0
  hydrated_bloc: ^11.0.0
  intl: any
  markdown: ^7.3.1
  material_color_utilities: any
  package_info_plus: ^10.2.1
  path_provider: ^2.1.6
  pub_semver: ^2.2.0
  relative_time: ^5.0.0
  rxdart: ^0.28.0
  share_plus: ^13.3.0
  shared_preferences: ^2.5.5
  sliver_tools: ^0.2.12
  super_sliver_list: ^0.4.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  leancode_lint: ^27.0.0

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
    - family: NotoSansMono
      fonts:
        - asset: assets/fonts/NotoSansMono-Regular.ttf
