import 'dart:convert';

import 'package:flutter/services.dart';
import 'package:glider/common/utils/public_suffix.dart';

/// Where a brand's icon lives in the Simple Icons CDN.
typedef BrandIcon = ({String slug, String url});

const _assetPath = 'assets/simple_icons/domains.json';

Map<String, String>? _domains;
String? _version;
Future<void>? _loading;

/// Loads the bundled domain index, once per process.
///
/// The index is generated by tool/update_simple_icons_map.py and carries the
/// simple-icons version it was built from, so the URLs it implies can never
/// point at a release the slugs did not come from.
Future<void> _load() async {
  if (_domains != null) return;
  return _loading ??= () async {
    final raw = await rootBundle.loadString(_assetPath);
    final decoded = json.decode(raw) as Map<String, dynamic>;
    _version = decoded['version'] as String;
    _domains = (decoded['domains'] as Map<String, dynamic>)
        .cast<String, String>();
  }();
}

/// The brand icon for [host], or null if Simple Icons has nothing for it.
///
/// Falls back to the registrable domain, so blog.cloudflare.com resolves the
/// same mark as cloudflare.com -- but no further, so a site on a public
/// suffix such as github.io keeps its own identity. Hosts are indexed without
/// a leading www.
Future<BrandIcon?> brandIconFor(String host) async {
  await Future.wait([_load(), ensurePublicSuffixListLoaded()]);
  final domains = _domains!;
  final normalised = host.toLowerCase().replaceFirst(RegExp('^www.'), '');
  final parent = registrableDomain(normalised);

  final slug =
      domains[normalised] ??
      (parent != null && parent != normalised ? domains[parent] : null);
  if (slug == null) return null;

  return (
    slug: slug,
    url: 'https://cdn.jsdelivr.net/npm/simple-icons@$_version/icons/$slug.svg',
  );
}

/// Test seam: replaces the bundled index so lookups can run without assets.
void debugSetBrandIconIndex(Map<String, String> domains, {String? version}) {
  _domains = domains;
  _version = version ?? 'test';
  _loading = null;
}
