name: glider_domain
version: 0.1.0+1
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.13.0 <4.0.0"

dependencies:
  equatable: ^2.1.0
  flutter:
    sdk: flutter
  glider_data:
    path: ../glider_data
  html: ^0.15.6
  material_color_utilities: any
  package_info_plus: ^10.2.1
  pub_semver: ^2.2.0
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  leancode_lint: ^27.0.0
