include: package:leancode_lint/analysis_options.yaml

plugins:
  leancode_lint: any

analyzer:
  errors:
    included_file_warning: ignore
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
