name: glider_data
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.13.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  collection: any
  flutter_secure_storage: ^11.0.0
  html: ^0.15.6
  http: ^1.6.0
  shared_preferences: ^2.5.5

dev_dependencies:
  leancode_lint: ^27.0.0
